version: 2.1
orbs:
  slack: circleci/slack@4.1.4
jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker

      - slack/notify: // OPTION1: this one works
          event: pass
          channel: idrottens-notify
          custom: |
                {
  "text": "",
  "blocks": [
    {
      "type": "header",
      "text": {
        "type": "plain_text",
        "text": "Deployment Successful! :tada:",
        "emoji": true
      }
    },
    {
      "type": "section",
      "fields": [
        {
          "type": "mrkdwn",
          "text": "*Project*:\\n$CIRCLE_PROJECT_REPONAME"
        },
        {
          "type": "mrkdwn",
          "text": "*When*:\\n$(date +'%m/%d/%Y %T')"
        },
        {
          "type": "mrkdwn",
          "text": "*Environment*:\\n$CIRCLE_BRANCH"
        },
        {
          "type": "mrkdwn",
          "text": "*Tag*:\\n$CIRCLE_TAG"
        }
      ],
      "accessory": {
        "type": "image",
        "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
        "alt_text": "CircleCI logo"
      }
    },
    {
      "type": "actions",
      "elements": [
        {
          "type": "button",
          "text": {
            "type": "plain_text",
            "text": "View Job"
          },
          "url": "${CIRCLE_BUILD_URL}"
        }
      ]
    }
  ]
}
